version: '3'
services:
   Eva:
      build:
         context: ./GrupoT/Equipo
      container_name: EvaM-container

   Pablo:
      build:
         context: ./GrupoT/Pablo
      container_name: Pablo-container

   EnriqueM:
      build:
         context: ./GrupoT/Equipo
      container_name: EnriqueM-containe
