services:
  jesus-arias:
    build: ./jesus-arias
    container_name: contenedor-jesus

  angel:
    build:
      context: ./angel
    container_name: angel-container

  santiago-cuevas:
    build:
      context: ./santiago-cuevas
    container_name: santiago-cuevas-container

  antonio:
    build:
      context: ./antonio
    container_name: antonio-container

  steve:
    build:
      context: ./steve
    container_name: mi-imagen-steve

  maria:
    build:
      context: ./maria
    container_name: maria-container

networks:
  default:
